# Generated by Django 5.0.6 on 2024-06-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polehaveoptions',
            name='user_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pole.poletable'),
        ),
    ]
