# Generated by Django 5.0.6 on 2024-06-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0002_polehaveoptions_user_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polehaveoptions',
            old_name='option_1',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='polehaveoptions',
            name='option_2',
        ),
    ]
