# Generated by Django 5.0.6 on 2024-07-01 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0003_rename_option_1_polehaveoptions_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user_pole',
            new_name='user_option',
        ),
        migrations.AddField(
            model_name='vote',
            name='user_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pole.poletable'),
        ),
    ]
